//! Explicit native-shell qualification; never substitutes generation for execution.
#![cfg(target_os = "linux")]

use dev_tools_command::{run_bounded_command, BoundedCommand};
use dev_tools_conformance::PUBLIC_PRODUCTS;
use std::{
    collections::BTreeMap,
    ffi::OsString,
    fs,
    path::{Path, PathBuf},
    time::Duration,
};

fn configured_path(key: &str) -> PathBuf {
    let path = PathBuf::from(std::env::var_os(key).unwrap_or_else(|| panic!("set {key}")));
    assert!(
        path.is_absolute() && path.exists(),
        "{key} must name an existing absolute path"
    );
    path
}

fn run(
    executable: &Path,
    args: &[OsString],
    env: &BTreeMap<OsString, OsString>,
    cwd: &Path,
) -> String {
    let output = run_bounded_command(&BoundedCommand {
        executable,
        arguments: args,
        environment: env,
        cwd: Some(cwd),
        timeout: Duration::from_secs(20),
        output_limit: 2 << 20,
    })
    .expect("bounded native probe");
    assert!(
        output.status.success(),
        "{}: {:?}\n{}",
        executable.display(),
        output.status,
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        output.stderr.is_empty(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("UTF-8 completion output")
}

fn qualify(shell: &str, shell_key: &str) {
    let binaries = configured_path("DEV_TOOLS_NATIVE_BIN_DIR");
    let runtime = configured_path(shell_key);
    let pty = (shell == "elvish").then(|| configured_path("DEV_TOOLS_TEST_SCRIPT"));
    for product in PUBLIC_PRODUCTS {
        let sandbox = tempfile::tempdir().expect("private shell sandbox");
        let root = sandbox.path();
        let mut env = BTreeMap::new();
        for (key, child) in [
            ("HOME", "home"),
            ("XDG_CONFIG_HOME", "config"),
            ("XDG_DATA_HOME", "data"),
            ("XDG_CACHE_HOME", "cache"),
            ("XDG_STATE_HOME", "state"),
            ("XDG_RUNTIME_DIR", "runtime"),
        ] {
            let path = root.join(child);
            fs::create_dir(&path).expect("isolated shell directory");
            env.insert(key.into(), path.into_os_string());
        }
        for (key, value) in [
            ("PATH", "/usr/bin:/bin"),
            ("TERM", "dumb"),
            ("POWERSHELL_TELEMETRY_OPTOUT", "1"),
            ("POWERSHELL_UPDATECHECK", "Off"),
            ("DOTNET_CLI_TELEMETRY_OPTOUT", "1"),
        ] {
            env.insert(key.into(), value.into());
        }
        let generated = run(
            &binaries.join(product.name),
            &["completion".into(), shell.into()],
            &env,
            root,
        );
        assert!(!generated.is_empty());
        let extension = if shell == "powershell" { "ps1" } else { shell };
        let completion = root.join(format!("completion.{extension}"));
        fs::write(&completion, &generated).expect("stage generated bytes unchanged");
        env.insert(
            "COMPLETION_SCRIPT".into(),
            completion.clone().into_os_string(),
        );
        env.insert("PRODUCT_NAME".into(), product.name.into());
        let product_probe = match product.name {
            "update-all" => ("runs prune --dry-r", "--dry-run"),
            "dev-auth" => ("workload bind plan --command-n", "--command-name"),
            "dev-cache" => ("config init-root --force-c", "--force-config"),
            "sync-configs" => ("logs prune --max-r", "--max-runs"),
            "skills-sync" => ("lock repair --agent-link-p", "--agent-link-policy"),
            "release-admin" => ("root build --release-public-k", "--release-public-key"),
            "artifact-update" => ("config apply --ex", "--expect"),
            _ => panic!("add a product-owned nested probe for {}", product.name),
        };
        let mut probes = vec![
            ("build-info --j", "--json"),
            ("", "completion"),
            product_probe,
        ];
        if shell == "elvish" && product.name == "dev-auth" {
            probes.push(("workload bind plan --target s", "structured"));
        }
        for (words, expected) in probes {
            let words = if shell == "zsh" && words.is_empty() {
                "comp"
            } else {
                words
            };
            env.insert(
                "PROBE_LINE".into(),
                format!("{} {words}", product.name).into(),
            );
            let (program, args) = match shell {
                "bash" => {
                    let probe = root.join("probe.bash");
                    fs::write(
                        &probe,
                        r#"source "$COMPLETION_SCRIPT" || exit 1
registration=$(complete -p "$PRODUCT_NAME" 2>/dev/null) || exit 0
read -r -a parts <<< "$registration"
function_name=
for ((index=0; index+1<${#parts[@]}; index++)); do
    if [[ ${parts[index]} == -F ]]; then function_name=${parts[index+1]}; break; fi
done
[[ -n $function_name ]] || exit 1
read -r -a COMP_WORDS <<< "$PROBE_LINE"
if [[ $PROBE_LINE == *' ' ]]; then COMP_WORDS+=(''); fi
COMP_CWORD=$((${#COMP_WORDS[@]}-1))
"$function_name" "$PRODUCT_NAME" "${COMP_WORDS[COMP_CWORD]}" "${COMP_WORDS[COMP_CWORD-1]}"
printf '%s\n' "${COMPREPLY[@]}"
"#,
                    )
                    .expect("stage native Bash completion probe");
                    (
                        runtime.as_path(),
                        vec![
                            "--noprofile".into(),
                            "--norc".into(),
                            probe.into_os_string(),
                        ],
                    )
                }
                "fish" => (
                    runtime.as_path(),
                    vec![
                        "--no-config".into(),
                        "-c".into(),
                        "source $COMPLETION_SCRIPT; complete -C $PROBE_LINE".into(),
                    ],
                ),
                "powershell" => {
                    let probe = root.join("probe.ps1");
                    fs::write(&probe, "$ErrorActionPreference = 'Stop'\n. $env:COMPLETION_SCRIPT\n[System.Management.Automation.CommandCompletion]::CompleteInput($env:PROBE_LINE, $env:PROBE_LINE.Length, $null).CompletionMatches | ForEach-Object { $_.CompletionText }\n").expect("stage native PowerShell probe");
                    (
                        runtime.as_path(),
                        vec![
                            "-NoLogo".into(),
                            "-NoProfile".into(),
                            "-NonInteractive".into(),
                            "-File".into(),
                            probe.into_os_string(),
                        ],
                    )
                }
                "elvish" => {
                    let probe = root.join("probe.elv");
                    // All words here are fixed test-owned command/option tokens.
                    let arguments = if words.is_empty() { "''" } else { words };
                    fs::write(&probe, format!("eval (slurp < $E:COMPLETION_SCRIPT)\n$edit:completion:arg-completer[$E:PRODUCT_NAME] $E:PRODUCT_NAME {arguments} | each {{|candidate| echo $candidate }}\nexit\n")).expect("stage native Elvish editor probe");
                    (
                        pty.as_deref().expect("explicit PTY executable"),
                        vec![
                            "-q".into(),
                            "-e".into(),
                            "-E".into(),
                            "never".into(),
                            "-O".into(),
                            "/dev/null".into(),
                            "--".into(),
                            runtime.as_os_str().into(),
                            "-rc".into(),
                            probe.into_os_string(),
                        ],
                    )
                }
                "zsh" => {
                    let probe = root.join("probe.zsh");
                    fs::write(&probe, r#"zmodload zsh/zpty || exit 1
zpty native "${(q)TASK_ZSH_RUNTIME}" -f || exit 1
TRAPEXIT() { zpty -d native 2>/dev/null }
zpty -w native 'autoload -Uz compinit; compinit -D; source "$COMPLETION_SCRIPT"; typeset -a native_matches; compadd() { if (( ${argv[(I)-[ADO]]} )); then builtin compadd "$@"; return; fi; local -a native_candidates; builtin compadd -O native_candidates "$@"; native_matches+=("${native_candidates[@]}"); builtin compadd "$@" }; report() { print -r --; for candidate in "${native_matches[@]}"; do print -r -- "NATIVE_CANDIDATE:$candidate"; done; print -r -- "NATIVE_RESULT:$BUFFER"; print -r -- NATIVE_RESULT_${:-END}; BUFFER=exit; zle accept-line }; zle -N report; bindkey "^X^G" report'
zpty -w -n native "$PROBE_LINE"$'\t\030\007'
zpty -r -m native output '*NATIVE_RESULT_END*' || exit 1
print -r -- "$output"
"#).expect("stage native Zsh editor probe");
                    env.insert("TASK_ZSH_RUNTIME".into(), runtime.as_os_str().into());
                    (runtime.as_path(), vec!["-f".into(), probe.into_os_string()])
                }
                _ => unreachable!("test-owned shell selector"),
            };
            let output = run(program, &args, &env, root);
            let has_candidate = |output: &str| {
                if shell == "elvish" {
                    // Elvish filters candidates in its editor, after invoking this function.
                    !output.contains("Exception")
                        && output.contains(&format!("complex-candidate {expected} "))
                } else if shell == "zsh" {
                    output
                        .lines()
                        .any(|line| line.strip_prefix("NATIVE_CANDIDATE:") == Some(expected))
                } else {
                    output
                        .lines()
                        .any(|line| line.split('\t').next() == Some(expected))
                }
            };
            assert!(
                has_candidate(&output),
                "{} {shell} {words}: {output}",
                product.name
            );
            // A fresh native process with registration removed must lose the candidate.
            // This catches probes accidentally satisfied by built-in or ambient completions.
            let empty = if shell == "elvish" {
                "set edit:completion:arg-completer[$E:PRODUCT_NAME] = {|@words| }\n"
            } else {
                ""
            };
            fs::write(&completion, empty).expect("stage negative registration control");
            let negative = run(program, &args, &env, root);
            assert!(
                !has_candidate(&negative),
                "{} {shell} candidate survived removal: {negative}",
                product.name
            );
            fs::write(&completion, &generated).expect("restore generated bytes unchanged");
        }
    }
}

#[test]
#[ignore = "requires explicitly configured product binaries and native Fish"]
fn native_fish() {
    qualify("fish", "DEV_TOOLS_TEST_FISH");
}

#[test]
#[ignore = "requires explicitly configured product binaries and native PowerShell"]
fn native_powershell() {
    qualify("powershell", "DEV_TOOLS_TEST_POWERSHELL");
}

#[test]
#[ignore = "requires explicitly configured product binaries, native Elvish and util-linux script"]
fn native_elvish() {
    qualify("elvish", "DEV_TOOLS_TEST_ELVISH");
}

#[test]
#[ignore = "requires explicitly configured product binaries and native Zsh with zpty"]
fn native_zsh() {
    qualify("zsh", "DEV_TOOLS_TEST_ZSH");
}

#[test]
#[ignore = "requires explicitly configured product binaries and native Bash"]
fn native_bash() {
    qualify("bash", "DEV_TOOLS_TEST_BASH");
}
